package org.app.generator;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class CountryCapital {
    // ISO‑2 → capital city (political)
    private static final Map<String, String> CAPITALS;

    static {
        Map<String, String> map = new HashMap<>();
        map.put("AF", "Kabul");
        map.put("AL", "Tirana");
        map.put("DZ", "Algiers");
        map.put("AD", "Andorra la Vella");
        map.put("AO", "Luanda");
        map.put("AG", "Saint John's");
        map.put("AR", "Buenos Aires");
        map.put("AM", "Yerevan");
        map.put("AU", "Canberra");
        map.put("AT", "Vienna");
        map.put("AZ", "Baku");
        map.put("BS", "Nassau");
        map.put("BH", "Manama");
        map.put("BD", "Dhaka");
        map.put("BB", "Bridgetown");
        map.put("BY", "Minsk");
        map.put("BE", "Brussels");
        map.put("BZ", "Belmopan");
        map.put("BJ", "Porto‑Novo");
        map.put("BT", "Thimphu");
        map.put("BO", "Sucre");
        map.put("BA", "Sarajevo");
        map.put("BW", "Gaborone");
        map.put("BR", "Brasília");
        map.put("BN", "Bandar Seri Begawan");
        map.put("BG", "Sofia");
        map.put("BF", "Ouagadougou");
        map.put("BI", "Gitega");
        map.put("CV", "Praia");
        map.put("KH", "Phnom Penh");
        map.put("CM", "Yaoundé");
        map.put("CA", "Ottawa");
        map.put("CF", "Bangui");
        map.put("TD", "N'Djamena");
        map.put("CL", "Santiago");
        map.put("CN", "Beijing");
        map.put("CO", "Bogotá");
        map.put("KM", "Moroni");
        map.put("CG", "Brazzaville");
        map.put("CD", "Kinshasa");
        map.put("CR", "San José");
        map.put("CI", "Yamoussoukro");
        map.put("HR", "Zagreb");
        map.put("CU", "Havana");
        map.put("CY", "Nicosia");
        map.put("CZ", "Prague");
        map.put("DK", "Copenhagen");
        map.put("DJ", "Djibouti");
        map.put("DM", "Roseau");
        map.put("DO", "Santo Domingo");
        map.put("EC", "Quito");
        map.put("EG", "Cairo");
        map.put("SV", "San Salvador");
        map.put("GQ", "Malabo");
        map.put("ER", "Asmara");
        map.put("EE", "Tallinn");
        map.put("SZ", "Mbabane");
        map.put("ET", "Addis Ababa");
        map.put("FJ", "Suva");
        map.put("FI", "Helsinki");
        map.put("FR", "Paris");
        map.put("GA", "Libreville");
        map.put("GM", "Banjul");
        map.put("GE", "Tbilisi");
        map.put("DE", "Berlin");
        map.put("GH", "Accra");
        map.put("GR", "Athens");
        map.put("GD", "St. George's");
        map.put("GT", "Guatemala City");
        map.put("GN", "Conakry");
        map.put("GW", "Bissau");
        map.put("GY", "Georgetown");
        map.put("HT", "Port‑au‑Prince");
        map.put("HN", "Tegucigalpa");
        map.put("HU", "Budapest");
        map.put("IS", "Reykjavík");
        map.put("IN", "New Delhi");
        map.put("ID", "Jakarta");
        map.put("IR", "Tehran");
        map.put("IQ", "Baghdad");
        map.put("IE", "Dublin");
        map.put("IL", "Jerusalem");
        map.put("IT", "Rome");
        map.put("JM", "Kingston");
        map.put("JP", "Tokyo");
        map.put("JO", "Amman");
        map.put("KZ", "Astana");
        map.put("KE", "Nairobi");
        map.put("KI", "Tarawa");
        map.put("KP", "Pyongyang");
        map.put("KR", "Seoul");
        map.put("KW", "Kuwait City");
        map.put("KG", "Bishkek");
        map.put("LA", "Vientiane");
        map.put("LV", "Riga");
        map.put("LB", "Beirut");
        map.put("LS", "Maseru");
        map.put("LR", "Monrovia");
        map.put("LY", "Tripoli");
        map.put("LI", "Vaduz");
        map.put("LT", "Vilnius");
        map.put("LU", "Luxembourg");
        map.put("MG", "Antananarivo");
        map.put("MW", "Lilongwe");
        map.put("MY", "Kuala Lumpur");
        map.put("MV", "Malé");
        map.put("ML", "Bamako");
        map.put("MT", "Valletta");
        map.put("MH", "Majuro");
        map.put("MR", "Nouakchott");
        map.put("MU", "Port Louis");
        map.put("MX", "Mexico City");
        map.put("FM", "Palikir");
        map.put("MD", "Chișinău");
        map.put("MC", "Monaco");
        map.put("MN", "Ulaanbaatar");
        map.put("ME", "Podgorica");
        map.put("MA", "Rabat");
        map.put("MZ", "Maputo");
        map.put("MM", "Naypyidaw");
        map.put("NA", "Windhoek");
        map.put("NR", "Yaren District");
        map.put("NP", "Kathmandu");
        map.put("NL", "Amsterdam");
        map.put("NZ", "Wellington");
        map.put("NI", "Managua");
        map.put("NE", "Niamey");
        map.put("NG", "Abuja");
        map.put("MK", "Skopje");
        map.put("NO", "Oslo");
        map.put("OM", "Muscat");
        map.put("PK", "Islamabad");
        map.put("PW", "Ngerulmud");
        map.put("PA", "Panama City");
        map.put("PG", "Port Moresby");
        map.put("PY", "Asunción");
        map.put("PE", "Lima");
        map.put("PH", "Manila");
        map.put("PL", "Warsaw");
        map.put("PT", "Lisbon");
        map.put("QA", "Doha");
        map.put("RO", "Bucharest");
        map.put("RU", "Moscow");
        map.put("RW", "Kigali");
        map.put("KN", "Basseterre");
        map.put("LC", "Castries");
        map.put("VC", "Kingstown");
        map.put("WS", "Apia");
        map.put("SM", "San Marino");
        map.put("ST", "São Tomé");
        map.put("SA", "Riyadh");
        map.put("SN", "Dakar");
        map.put("RS", "Belgrade");
        map.put("SC", "Victoria");
        map.put("SL", "Freetown");
        map.put("SG", "Singapore");
        map.put("SK", "Bratislava");
        map.put("SI", "Ljubljana");
        map.put("SB", "Honiara");
        map.put("SO", "Mogadishu");
        map.put("ZA", "Pretoria");
        map.put("SS", "Juba");
        map.put("ES", "Madrid");
        map.put("LK", "Sri Jayawardenepura Kotte");
        map.put("SD", "Khartoum");
        map.put("SR", "Paramaribo");
        map.put("SE", "Stockholm");
        map.put("CH", "Bern");
        map.put("SY", "Damascus");
        map.put("TW", "Taipei");
        map.put("TJ", "Dushanbe");
        map.put("TZ", "Dodoma");
        map.put("TH", "Bangkok");
        map.put("TL", "Dili");
        map.put("TG", "Lomé");
        map.put("TO", "Nukuʻalofa");
        map.put("TT", "Port of Spain");
        map.put("TN", "Tunis");
        map.put("TR", "Ankara");
        map.put("TM", "Ashgabat");
        map.put("TV", "Funafuti");
        map.put("UG", "Kampala");
        map.put("UA", "Kyiv");
        map.put("AE", "Abu Dhabi");
        map.put("GB", "London");
        map.put("US", "Washington, D.C.");
        map.put("UY", "Montevideo");
        map.put("UZ", "Tashkent");
        map.put("VU", "Port Vila");
        map.put("VA", "Vatican City");
        map.put("VE", "Caracas");
        map.put("VN", "Hanoi");
        map.put("YE", "Sana'a");
        map.put("ZM", "Lusaka");
        map.put("ZW", "Harare");
        CAPITALS = Collections.unmodifiableMap(map);
    }

    /**
     * @param countryCode ISO 3166‑1 alpha‑2
     * @return the capital city, or null if not found
     */
    public static String getCapital(String countryCode) {
        if (countryCode == null) return null;
        return CAPITALS.get(countryCode.toUpperCase());
    }
}
